CREATE TABLE AIRLINE(
  ID BIGINT AUTO_INCREMENT NOT NULL
  ,NAME         VARCHAR(25) NOT NULL
  ,DIGIT_CODE_2 VARCHAR(2) NOT NULL
  ,DIGIT_CODE_3 VARCHAR(3) NOT NULL
  ,COUNTRY      VARCHAR(100) NOT NULL
  ,PRIMARY KEY (ID)
);
INSERT INTO AIRLINE(NAME,DIGIT_CODE_2,DIGIT_CODE_3,COUNTRY) VALUES ('Air China','CA','CCA','China');
INSERT INTO AIRLINE(NAME,DIGIT_CODE_2,DIGIT_CODE_3,COUNTRY) VALUES ('China Southern Airlines','CZ','CSN','China');
INSERT INTO AIRLINE(NAME,DIGIT_CODE_2,DIGIT_CODE_3,COUNTRY) VALUES ('Southwest Airlines','WN','SWA','United States');
INSERT INTO AIRLINE(NAME,DIGIT_CODE_2,DIGIT_CODE_3,COUNTRY) VALUES ('Turkish Airlines','TK','THY','Turkey');
INSERT INTO AIRLINE(NAME,DIGIT_CODE_2,DIGIT_CODE_3,COUNTRY) VALUES ('United Airlines','UA','UAL','United States');
INSERT INTO AIRLINE(NAME,DIGIT_CODE_2,DIGIT_CODE_3,COUNTRY) VALUES ('WestJet','WS','WJA','Canada');